### ISSUE TITLE
Implement color recommendation for firefox

### ISSUE THREAD

**Issue by hendriku** [dhbw-timetable/rablabla#56]
You see the color difference from Chrome (left) to the most recent Firefox on macOS:
<img width="1047" alt="bildschirmfoto 2017-11-04 um 20 25 11" src="https://user-images.githubusercontent.com/8998518/32408739-55b29d3e-c19e-11e7-8977-08089c4527b6.png">

**Comment by MalteBartels** [comment]
I'm not sure, if we can do something about it...

**Comment by hendriku** [comment]
Does not seem so. Let us keep it open till we have an answer for this. I'd suggest marking it as a late feature

**Comment by hendriku** [comment]
Hey, what about putting this onto the whole site?

```css
.et_pb_main_blurb_image {
   -moz-filter: grayscale(100%);
   -moz-transition: .5s ease-in-out;
   -o-filter: grayscale(100%);
   -o-transition: .5s ease-in-out;
   -webkit-filter: grayscale(100%);
   -webkit-transition: .5s ease-in-out;
}
```
https://support.mozilla.org/de/questions/1129117
